name: isohttpd
description: A lightweight http server that runs in an isolate. Router and logs are included.
version: 0.5.0
homepage: https://github.com/synw/isohttpd

environment:
  sdk: ">=2.2.0 <3.0.0"

dev_dependencies:
  test: ^1.6.5

dependencies:
  pedantic: ^1.9.2
  extra_pedantic: ^1.2.0
  meta: ^1.2.4
  body_parser: ^1.1.1
  iso: ^0.3.0
  path: ^1.7.0
  emodebug: ^0.5.0
