name: isohttpd
description: A lightweight http server that runs in an isolate
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0

dependencies:
  meta: ^1.1.6
  body_parser: ^1.1.1
  iso: ^0.1.0
